### PR TITLE
Menu.c/.h rewrite, build system update, draw.c/.h cleanup & console functionality

### PR DESCRIPTION
**Pull request by d0k3**
This is a big one... Mostly under the hood changes, though.

While the menu.c/.h code looks like something completely different now, it actually is your code, but is rebased around a MenuEntry struct system. If you want to change something now, you don't have to do so in 10 different places, but only in one.

draw.c/draw.h and the corresponding function calls are cleaned up. That means: unneeded stuff (such as clearing the screen before loading a splash screen) is gone. Other stuff got combined into one function (where it made sense).

console.c/console.h was tampered with - badly. As I see it not by you but by the guy you got it from ;). I fixed it and restored the console functionality, which means we've now got scrolling :).

As for actual changes (ie. not only under the hood):
o The scrolling console, of course
o UI files can now be put into /3DS/[APP_TITLE]/UI or /D9UI (APP_TITLE is in AppInfo, it is 'Decrypt9' by default)
o Take a look into the new resources dir - you can easily change app title, description and icon there
o For a pleasant surprise, try 'make release' 
o make bootstrap, make gateway, make brahma work as well
o I fixed some texts in the menu system (wrong names for features, f.e.)
o DANGER_ZONE define is back again - you can now compile a 'safe' version with working menu system. DANGER_ZONE is enabled by default.

I suggest you take a look to determine if everything is still working as it used to - it should.

### CODE REVIEW

**Comment by Shadowtrance** [comment]
Everything appears to be good :)

Except for the spider version not working if i build with make release. It works as normal if i use make gateway separately though.

**Comment by d0k3** [comment]
That's pretty strange, as with the release goal, the launcher.dat is still built in the exact same way... Did you put the UI files into \D9UI or into \3DS\Decrypt9\UI (both should work, I'm just trying to figure the problem out).

**Comment by d0k3** [comment]
Okay, I found the reason behind the problem, and coincidentially also the reason why my Launcher.dat never worked. For the Launcher.dat to work, Decrypt9.bin has to be compiled from scratch, with the changed parameters. However, the build system doesn't do this at the moment, it just uses the Brahma compatible Decrypt9.bin.

I'll find a solution soon.

**Comment by d0k3** [comment]
Okay.... could you try it now? I fixed it and squashed the commit into the 'Update makefiles' commit. Another problem solved :+1:

**Comment by Shadowtrance** [comment]
Yep that seems to have solved that problem. :+1:

**Pull request merged**
