### PR TITLE
Remove uneccessary stuff from Brahma loader

### PR DESCRIPTION
**Pull request by d0k3**
Smaller 3DSX + more beautiful code.

### CODE REVIEW

**Comment by Shadowtrance** [comment]
Can you split these (and any other changes you may make) into separate pull requests (one commit per request) rather than lumping them all in one PR please. Just easier to inspect things that way. :)

**Comment by d0k3** [comment]
Yeah, sorry! But you can checkout my commits. And I don't know how to split the pull request into single commits. About your comments: There is only one really big commit, the changed brahma_loader. The *.elf is moved from the brahma_loader directory, The new build.bat creates the data dir where it is needed, I think that's better than including the dummy file.

**Comment by d0k3** [comment]
... and you should start reviewing from the top ;)

**Comment by Shadowtrance** [comment]
I did start reviewing at the top. :P And have my local copy here in front of me testing changes. :) And yeah brahma got stripped down to it's underpants haha not much left.

**Comment by Shadowtrance** [comment]
And no something is going wrong with the data folder, i just watched it compile on one screen with the brahma_loader folder open on the other screen, for some reason it doesn't actually make a data folder but rather a "data" file (just a blank white file with the size of the payload.bin), i dunno what's going on there. Strange.

**Comment by d0k3** [comment]
Correct, you have to make the data folder earlier :).
ie: mkdir brahma_loader\data before make in the main directory

**Comment by Shadowtrance** [comment]
I fixed it, was the first makefile causing it so i added @mkdir data $(OUTPUT_D) before mv payload.bin $(OUTPUT_D) and removed that part from the build bat.

**Comment by Shadowtrance** [comment]
I fixed it. first makefile was causing it so i  added " @mkdir $(OUTPUT_D) " before " mv payload.bin $(OUTPUT_D) " and removed that part from the build.bat

**Comment by d0k3** [comment]
Alright, so, do I need to change anything for my pull request? I'll be able to do so tomorrow.

**Comment by Shadowtrance** [comment]
Yeah looks fine now, I'll add the data folder change myself.

**Pull request merged**
